"""
/chat endpoint — Local LLM inference via AIR LLM
=================================================

This router exposes POST /api/v1/chat for any client (frontend, Node backend,
or third-party tool) that wants to send a natural-language prompt to the
locally-running model.

The AI provider is resolved through the abstraction layer in app/ai/, so
swapping the underlying model requires only environment variable changes —
no code modifications here.
"""

from __future__ import annotations

import logging
from typing import Optional

from fastapi import APIRouter, HTTPException, status
from pydantic import BaseModel, Field

from app.ai.airllm_service import generate_response, get_provider

logger = logging.getLogger(__name__)

router = APIRouter(tags=["chat"])


# ---------------------------------------------------------------------------
# Request / Response schemas
# ---------------------------------------------------------------------------

class ChatRequest(BaseModel):
    prompt: str = Field(
        ...,
        min_length=1,
        max_length=4096,
        description="The user's message or instruction to the model.",
        examples=["Explain the concept of gradient descent in simple terms."],
    )
    max_new_tokens: Optional[int] = Field(
        default=256,
        ge=1,
        le=2048,
        description="Maximum number of tokens the model may generate.",
    )


class ChatResponse(BaseModel):
    response: str = Field(..., description="Text generated by the local LLM.")
    provider: str = Field(..., description="Active AI provider identifier.")
    prompt_length: int = Field(..., description="Character count of the received prompt.")


# ---------------------------------------------------------------------------
# Endpoint
# ---------------------------------------------------------------------------

@router.post(
    "/chat",
    response_model=ChatResponse,
    summary="Send a prompt to the local LLM",
    description=(
        "Accepts a text prompt and returns an AI-generated response from the "
        "locally running model (AIR LLM / Mistral by default). "
        "The model can be changed without modifying this endpoint — see "
        "app/ai/airllm_service.py for configuration details."
    ),
)
async def chat(request: ChatRequest) -> ChatResponse:
    """
    Route a prompt to the active LLM provider and return the response.

    The provider is a singleton initialised once at server startup; this
    handler simply delegates to it and wraps the result in a JSON response.
    """
    logger.info(
        f"[/chat] prompt_length={len(request.prompt)} "
        f"max_new_tokens={request.max_new_tokens}"
    )

    try:
        text = generate_response(
            prompt=request.prompt,
            max_new_tokens=request.max_new_tokens,
        )
    except RuntimeError as exc:
        # Raised when airllm is not installed or the model failed to load
        logger.error(f"[/chat] Provider error: {exc}")
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail=str(exc),
        )
    except Exception as exc:
        logger.error(f"[/chat] Inference error: {exc}", exc_info=True)
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Model inference failed. Check server logs for details.",
        )

    return ChatResponse(
        response=text,
        provider=get_provider().provider_name,
        prompt_length=len(request.prompt),
    )


# ---------------------------------------------------------------------------
# Provider info helper
# ---------------------------------------------------------------------------

@router.get(
    "/chat/provider",
    summary="Active LLM provider info",
    description="Returns the name of the currently loaded AI provider/model.",
)
async def provider_info() -> dict:
    """Useful for health dashboards and debugging."""
    return {"provider": get_provider().provider_name}
